//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// DataAnnotations tags added by hand

using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


namespace FellowshipTest.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("communication", Namespace = "", IsNullable = false)]
    public partial class Communication
    {

        private Household householdField;

        private Person personField;

        private communicationType communicationTypeField;

        private communicationGeneralType communicationGeneralTypeField;

        private string communicationValueField;

        private string searchCommunicationValueField;

        private bool listedField;

        private string communicationCommentField;

        //private System.Nullable<System.DateTime> createdDateField;
        private string createdDateField;
        //private System.Nullable<System.DateTime> lastUpdatedDateField;
        private string lastUpdatedDateField;

        private string uriField;

        private string idField;
        /*
        public communication() {
            this.createdDateField = new System.DateTime(0);
            this.lastUpdatedDateField = new System.DateTime(0);
        }
        */
        /// <remarks/>
        public Household household
        {
            get
            {
                return this.householdField;
            }
            set
            {
                this.householdField = value;
            }
        }

        /// <remarks/>
        public Person person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }

        /// <remarks/>
        public communicationType communicationType
        {
            get
            {
                return this.communicationTypeField;
            }
            set
            {
                this.communicationTypeField = value;
            }
        }

        /// <remarks/>
        public communicationGeneralType communicationGeneralType
        {
            get
            {
                return this.communicationGeneralTypeField;
            }
            set
            {
                this.communicationGeneralTypeField = value;
            }
        }

        /// <remarks/>
        public string communicationValue
        {
            get
            {
                return this.communicationValueField;
            }
            set
            {
                this.communicationValueField = value;
            }
        }

        /// <remarks/>
        public string searchCommunicationValue
        {
            get
            {
                return this.searchCommunicationValueField;
            }
            set
            {
                this.searchCommunicationValueField = value;
            }
        }

        /// <remarks/>
        [Display(Name = "Listed?")]
        public bool listed
        {
            get
            {
                return this.listedField;
            }
            set
            {
                this.listedField = value;
            }
        }

        /// <remarks/>
        [Display(Name = "Comment")]
        public string communicationComment
        {
            get
            {
                return this.communicationCommentField;
            }
            set
            {
                this.communicationCommentField = value;
            }
        }
        /* working around problem with deserializing datetimes
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lastUpdatedDate {
            get {
                return this.lastUpdatedDateField;
            }
            set {
                this.lastUpdatedDateField = value;
            }
        }
        */
        /// <remarks/>
        [Display(Name = "Created")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string createdDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        [Display(Name = "Last Updated")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string lastUpdatedDate
        {
            get
            {
                return this.lastUpdatedDateField;
            }
            set
            {
                this.lastUpdatedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class communicationType
    {

        private object nameField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public enum communicationGeneralType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,

        /// <remarks/>
        Email,

        /// <remarks/>
        Telephone,

        /// <remarks/>
        SocialMedia,

        /// <remarks/>
        Web,
    }
}